image: Visual Studio 2017 Preview
configuration: Release  

environment:
  SignClientSecret:
    secure: OGeYaIIqAmZBE4DUkbR2F3RUP5CXXPRt3oobQYg4yrc=
  SignClientUser:
    secure: uyweGSwxexnLy4dBNleW8tYcXTA291faj34PQV0ePxOTFSa5Cvf50jyICVP9mLGS
      
init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

install: 
  - cmd: nuget install SignClient -Version 0.9.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion  
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.2,android-26,android-25,extra-google-m2repository,extra-android-m2repository
  # on windows we need to accept sublicenses for the new tooling, wee. 30 is an arbitrary number,
  # but should be the maximum number of licenses we explicitly need to type "Y ENTER" for.
  # also, the sdkmanager in all its glory leaks a bit of output to stderr, and powershell
  # and appveyor interpret that as errors, and blows up. so, when piping in our "Y ENTER"
  # responses, we invoke cmd so we can redirect stderr to stdout, and tell it to --update itself.
  - ps: for($i=0;$i -lt 30;$i++) { $response += "y`n"}; $response | cmd /c '"C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager.bat" 2>&1' --update

before_build:
  - cmd: msbuild /t:restore xUnit.Devices.sln
  
build:
  verbosity: normal
  parallel: true
  project: xUnit.Devices.sln

after_build:  
  - cmd: msbuild src\xunit.runner.devices\xunit.runner.devices.csproj /t:pack /p:Configuration=Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  - ps: '.\SignClient\Sign-Package.ps1'
    
artifacts:
  - path: '*.nupkg'

test: off
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/xunit-xamarin/api/v2/package
  symbol_server: https://www.myget.org/F/xunit-xamarin/symbols/api/v2/package
  api_key:
    secure: w1p7TvDGit5RlN4XKLjDC12Kd43SQ5qwLgRGGXtjfHKX1Yf7ZAOYBW6pLUkPJFJ6
  artifact: /.*\.nupkg/

notifications:
- provider: Slack
  incoming_webhook:
    secure: k1oXe/zscPP/vX2kQXYNO1SkIMvN47r8BNA6gkM6z5+I8rKJD+g8C3+pbdARRuzUHAMO5vzD7TXeL6fMt5oIw0QBnuAGNBLx4EsBWllmPyw=
  channel: '#pulse'
  on_build_success: true
  on_build_failure: true